# Generated by Django 6.0.3 on 2026-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
