# Generated by Django 6.0.3 on 2026-03-17 07:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_workspace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodicMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(default='implementation', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('related_files', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='episodic_memories', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='SemanticMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('symbol', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='semantic_memories', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'file_path', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='WorkingMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(default='implementation', max_length=100)),
                ('summary', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='working_memories', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'scope')},
            },
        ),
    ]
