# Generated by Django 6.0.3 on 2026-03-19 07:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_memory_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='codebase_reference', max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('target_fingerprint', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('output_path', models.CharField(blank=True, max_length=1000)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='documentation_runs', to='core.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('markdown', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='sections', to='core.documentationrun')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('run', 'key')},
            },
        ),
    ]
