# Generated by Django 6.0.4 on 2026-04-23 10:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_user', models.BooleanField(default=False, verbose_name='Is user')),
                ('widget_script_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_html_url', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('translation_enabled', models.BooleanField(default=False, verbose_name='Translation enabled')),
                ('leads_enabled', models.BooleanField(default=False, verbose_name='Leads enabled')),
                ('whatsapp_license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_mails', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Lead Mails')),
                ('whatsapp_appkey', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_authkey', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('custom_rules', models.TextField(blank=True, default='')),
                ('chatbot_tone', models.CharField(choices=[('helpful chatbot', 'Helpful chatbot'), ('customer support agent', 'Customer Support Agent')], default='friendly', max_length=100)),
                ('role_behavior', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('customer_support', 'Customer Support'), ('Proactive Property Market Advisor - Matching Clients with Ideal Real Estate Solutions', 'Real Estate Professional')], default='friendly', max_length=200)),
                ('web_app_info', models.TextField()),
                ('conversation_behavior', models.TextField()),
                ('fallback_message', models.TextField()),
                ('header_color', models.CharField(default='#0b3d2c', max_length=7)),
                ('send_button_color', models.CharField(default='#0b3d2c', max_length=7)),
                ('header_text', models.CharField(default='Name', max_length=100)),
                ('welcome_message', models.TextField(default='Welcome! How may I help you?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='chatbot_logos/')),
                ('we_are_here_image', models.ImageField(blank=True, null=True, upload_to='chatbot_we_are_here/')),
                ('chat_toggle_image', models.ImageField(blank=True, null=True, upload_to='chatbot_toggle_images/')),
                ('business_info', models.TextField(default='Business Information')),
                ('faq', models.TextField(default='FAQ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='accounts.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
                ('lead_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('chat_summary', models.TextField(blank=True, null=True)),
                ('property_selection', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=255, null=True)),
                ('user_selections', models.JSONField(blank=True, null=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chatbot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Histories',
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('message', 'Bot Message'), ('buttons', 'Buttons')], max_length=20)),
                ('message', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.chatflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlowButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='accounts.flowstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PDFStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='pdfs/')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chatbot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('useful_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
