import React from 'react';
import { Bot, ShieldAlert, CheckCircle } from 'lucide-react';

export default function AIPanel({ summary, credibilityScore = 0 }) {
  const getScoreDetails = (score) => {
    if (score >= 80) {
      return {
        barColor: 'bg-[#1d4ed8]', // primary green from design system
        textColor: 'text-[#1d4ed8]',
        bgColor: 'bg-blue-50',
        icon: <CheckCircle className="w-5 h-5 text-[#1d4ed8]" />
      };
    }
    if (score >= 50) {
      return {
        barColor: 'bg-[#D97706]', // accent orange from design system
        textColor: 'text-[#D97706]',
        bgColor: 'bg-amber-50',
        icon: <ShieldAlert className="w-5 h-5 text-[#D97706]" />
      };
    }
    return {
      barColor: 'bg-rose-600',
      textColor: 'text-rose-700',
      bgColor: 'bg-rose-50',
      icon: <ShieldAlert className="w-5 h-5 text-rose-600" />
    };
  };

  const { barColor, textColor, bgColor, icon } = getScoreDetails(credibilityScore);

  return (
    <div className="bg-indigo-50/60 border border-indigo-100 rounded-xl p-6 shadow-sm">
      <div className="flex items-center gap-3 mb-5">
        <div className="p-2.5 bg-indigo-100 rounded-lg text-indigo-700 shadow-sm">
          <Bot className="w-6 h-6" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-[#0F172A] font-display">AI Analysis & Insights</h3>
          <p className="text-xs text-indigo-600/80 font-medium">Generated by C3MS Intelligence</p>
        </div>
      </div>

      <div className="space-y-6">
        <div>
          <h4 className="text-xs font-bold text-[#64748B] mb-2 uppercase tracking-wider">Automated Summary</h4>
          <div className="bg-white/80 rounded-lg p-4 border border-indigo-50 shadow-sm">
            <p className="text-[#0F172A] leading-relaxed text-sm">
              {summary || "No AI summary available for this complaint at this time."}
            </p>
          </div>
        </div>

        <div>
          <h4 className="text-xs font-bold text-[#64748B] mb-2 uppercase tracking-wider">Risk & Credibility Assessment</h4>
          <div className={`rounded-lg p-4 border border-white/50 shadow-sm ${bgColor}`}>
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                {icon}
                <span className="font-semibold text-[#0F172A]">Credibility Score</span>
              </div>
              <span className={`font-bold text-lg ${textColor}`}>{credibilityScore}/100</span>
            </div>
            
            <div className="w-full bg-white/60 rounded-full h-3 overflow-hidden border border-black/5">
              <div
                className={`h-full rounded-full ${barColor} transition-all duration-1000 ease-out relative overflow-hidden`}
                style={{ width: `${credibilityScore}%` }}
              >
                <div className="absolute inset-0 bg-white/20 w-full animate-[shimmer_2s_infinite] -translate-x-full" style={{ backgroundImage: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.4), transparent)' }}></div>
              </div>
            </div>
            
            <p className="text-xs text-[#64748B] mt-3 leading-tight">
              Score calculated based on historical data patterns, evidence metadata analysis, and cross-referencing similar verified reports in the district.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}