# Generated by Django 6.0.3 on 2026-03-16 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', models.CharField(default='Developer', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='backlog', max_length=50)),
                ('spec', models.JSONField(default=dict)),
                ('suggestions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('local_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('team_members', models.JSONField(default=list)),
                ('blueprint', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(default='Developer', max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Changeset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('ai_review', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changesets', to='core.feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changesets', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('by', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_history', to='core.feature')),
            ],
        ),
        migrations.CreateModel(
            name='FileDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('diff_content', models.TextField()),
                ('action', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=50)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_changed', to='core.changeset')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.project'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='running', max_length=50)),
                ('logs', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('tests', models.JSONField(default=list)),
                ('coverage', models.IntegerField(default=0)),
                ('suggestions', models.JSONField(default=list)),
                ('blockers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.feature')),
            ],
        ),
    ]
