# Generated by Django 5.0.8 on 2024-11-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'verbose_name_plural': 'Chat Histories'},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='lead_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='lead_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
