# Generated by Django 5.0.8 on 2024-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_chathistory_options_chathistory_is_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leads_enabled',
            field=models.BooleanField(default=False, verbose_name='Leads enabled'),
        ),
    ]
