# Generated by Django 5.0.8 on 2024-11-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_leads_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leads_enabled',
        ),
    ]
