# Generated by Django 5.0.8 on 2024-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_leads_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='role_behavior',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('customer_support', 'Customer Support'), ('Proactive Property Market Advisor - Matching Clients with Ideal Real Estate Solutions', 'Real Estate Professional')], default='friendly', max_length=200),
        ),
    ]
