# Generated by Django 5.0.8 on 2024-11-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_chatbot_role_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='lead_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
