# Generated by Django 5.0.8 on 2024-11-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_chathistory_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='chat_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
