# Generated by Django 5.0.8 on 2024-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chathistory_chat_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leads_enabled',
            field=models.BooleanField(default=False, verbose_name='Leads enabled'),
        ),
    ]
