# Generated by Django 5.0.8 on 2024-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_leads_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='conversation_behavior',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
