# Generated by Django 5.0.8 on 2024-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_chatbot_conversation_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chat_toggle_image',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_toggle_images/'),
        ),
    ]
