# Generated by Django 5.0.8 on 2024-12-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_chatbot_chat_toggle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lead_mails',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Lead Mails'),
        ),
    ]
