# Generated by Django 5.0.8 on 2025-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_product_discount_product_price_product_useful_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_appkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_authkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
