# Generated by Django 5.0.8 on 2025-01-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_whatsapp_appkey_user_whatsapp_authkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='business_info',
            field=models.TextField(default='Business Information'),
        ),
    ]
