# Generated by Django 5.0.8 on 2025-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_chatbot_business_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='faq',
            field=models.TextField(default='FAQ'),
        ),
    ]
