# Generated by Django 5.0.8 on 2025-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_chatbot_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='quick_access_buttons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
