# Generated by Django 5.0.8 on 2025-01-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_chatbot_quick_access_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='quick_access_buttons',
        ),
    ]
