# Generated by Django 5.0.8 on 2025-02-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_chatbot_quick_access_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='property_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
