# Generated by Django 5.0.8 on 2025-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_chathistory_property_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='budget_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
