# Generated by Django 5.1.5 on 2025-03-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_chatflow_flowstep_flowbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user_selections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
